### ISSUE TITLE
Failure to compile using CMakeFMTVS2017.sh with necessary dependancies installed

### ISSUE THREAD

**Issue by Klemet** [gcyr/FMT#2]
**Describe the bug**
On Windows 10, with Boost libraries and VS 2017 installed, the CMakeFMTVS2017.sh script fails to build anything.

Here is the following log : 
```

D:\Clement\Desktop\FMT-master>CMakeFMTVS2017.bat

D:\Clement\Desktop\FMT-master>call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"
The specified configuration type is missing.  The tools for the
configuration might not be installed.
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.18363.
Generating Build file for FMT 0.9.1
Found Python include here: C:/ProgramData/Miniconda3/include
Found Python library here: C:/ProgramData/Miniconda3/libs/python39.lib
Found Boost include here: D:/Clement/Downloads/boost_1_76_0
Found Boost libraries here: optimized;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_system-vc141-mt-x64-1_76.lib;debug;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_system-vc141-mt-gd-x64-1_76.lib;optimized;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_filesystem-vc141-mt-x64-1_76.lib;debug;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_filesystem-vc141-mt-gd-x64-1_76.lib;optimized;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_serialization-vc141-mt-x64-1_76.lib;debug;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_serialization-vc141-mt-gd-x64-1_76.lib;optimized;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_iostreams-vc141-mt-x64-1_76.lib;debug;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_iostreams-vc141-mt-gd-x64-1_76.lib;optimized;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_regex-vc141-mt-x64-1_76.lib;debug;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_regex-vc141-mt-gd-x64-1_76.lib;optimized;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_python39-vc141-mt-x64-1_76.lib;debug;D:/Clement/Downloads/boost_1_76_0/stage/lib/boost_python39-vc141-mt-gd-x64-1_76.lib
-- Could NOT find GDAL (missing: GDAL_LIBRARY GDAL_INCLUDE_DIR) (found version "GDAL_VERSION-NOTFOUND")
GDAL not found take a look at (https://github.com/OSGeo/gdal)
Compile GDAL with GEOS for more functionalities (https://github.com/libgeos/geos)
CMake Error at Modules/FindOSI.cmake:9 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:300 (find_package)


CMake Error at Modules/FindOSI.cmake:10 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:300 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/Clement/Desktop/FMT-master/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa pour .NET Framework
Copyright (C) Microsoft Corporation. Tous droits réservés.

MSBUILD : error MSB1009: Le fichier projet n'existe pas.
Commutateur : ALL_BUILD.vcxproj
CMake Error: Error processing file: D:/Clement/Desktop/FMT-master/cmake_install.cmake
```

**To Reproduce**
1. Build the boost libraries with zlib
2. Launch `CMakeFMTVS2017.sh` via a windows command prompt

**Expected behaviour**
It is expected that with the necessary dependencies for FMT, the script would succeed in building the libraries.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by gcyr** [comment]
What have you wrote next to -DOSI_DIR= in the CMakeFMTVS2017.bat ? I will add some warnings and fix the issue but I just want to make sure I can reproduce the bug. thanks!

**Comment by Klemet** [comment]
Allo, Guillaume ! On peut échanger en francais si tu préfère, et je mettrais mon commentaire en anglais pour d'autres utilisateurs/utilisatrices : ).

Le `CMakeFMTVS2017.bat` est le même que celui qui se trouve dans le repo actuellement. Ainsi, il y est écrit `-DOSI_DIR="C:/MrnMicro/Applic/Cbc-2.10.2/"`.

* * *
_English translation_

The `CMakeFMTVS2017.bat` file I have is the same that the one currently in the repository. Hence, it is written `-DOSI_DIR="C:/MrnMicro/Applic/Cbc-2.10.2/"`.

**Comment by gcyr** [comment]
Ha pas de problème merci beaucoup pour tes commentaires! Je vais ajouter des messages d'avertissements par rapport à l'existence du répertoire et des limitations par rapport aux dépendances.
So in the next commit I will add some warnings regarding the defined folders and fix the issue with the dependencies! 
Merci encore!

**Comment by Klemet** [comment]
Thanks for the update !

Looks like this first issue was fixed, but the file still won't compile properly. Now, a new issue is there.

Basically, the compilation stops, stating that a certain boost library file couldn't be opened (`libboost_serialization-vc141-mt-x64-1_76.lib`). However, this particular boost library file is present in the folder containing the other libraries, as is stated by the output just before the error (see red rectangle on this screenshot).

![image](https://user-images.githubusercontent.com/41070328/123485901-0eed8a00-d5d9-11eb-94b9-7b7634ad6d64.png)

Any idea why the compiler can't open `libboost_serialization-vc141-mt-x64-1_76.lib` ?

**Comment by gcyr** [comment]
I dont have specified static (libboost) library in the boost find_package in the cmake file so find_package looks for the dynamic lib (boost) and the linker is complaining because it wants the static one... I will find some time to fix this next week I guess...:)
