### ISSUE TITLE
FMTsolverinterface missing from Doxygen documentation.

### ISSUE THREAD

**Issue by Klemet** [gcyr/FMT#3]
The FMTsolverinterface class is small class, but might be an important one as it is used in many of the examples present in the repository.

However, it seems to be missing from the Doxygen documentation:

![image](https://user-images.githubusercontent.com/41070328/124338242-bdaf3e80-db74-11eb-871e-9f3502ed56d4.png)

It is, however, referred on the Doxygen page for the FMTlpsolver class:

![image](https://user-images.githubusercontent.com/41070328/124338153-52fe0300-db74-11eb-9d63-7a8f522dbdbc.png)

Maybe the issue is in https://github.com/gcyr/FMT/blob/master/Source/FMTsolverinterface.h or https://github.com/gcyr/FMT/blob/master/Source/FMTsolverinterface.cpp ?

**Comment by Klemet** [comment]
I try to fiddle around with the parameter of `FMTdoxygenconfig`, but to no avail. I can't get this class to appear in the documentation.

**Comment by BrunoForest** [comment]
FMTsolverinterface is an enumerator. When we have time, i will try to add it to the documentation. At this time, it looks like the enumerator documentation in FMT doesn't follow.

**Comment by Klemet** [comment]
Fantastic !!! Thanks, Bruno ! The links makes it extremely clear !
