### ISSUE TITLE
Area parser declared but not used in two example python example scripts.

### ISSUE THREAD

**Issue by Klemet** [gcyr/FMT#4]
In the following line, in the example file Initialareavariability.py, an area parser is declared; however, it doesn't seem to be use in the rest of the script :

 https://github.com/gcyr/FMT/blob/4ace3d3fa58ba2bd769bcb87ad176b69986a26b3/Examples/Python/Initialareavariability.py#L18

The same goes for Multiplesolutionvariability.py:

https://github.com/gcyr/FMT/blob/4ace3d3fa58ba2bd769bcb87ad176b69986a26b3/Examples/Python/Multiplesolutionvariability.py#L17

Is it normal ? From looking at the Doxygen documentation, it doesn't look like using the constructor for the class does anything else than create the object.

**Comment by BrunoForest** [comment]
It's an error, those line will be remove in the next commit. You don't need to declare an areaparser if you don't use it.
