### ISSUE TITLE
Use vcpkg for librairies on windows ?

### ISSUE THREAD

**Issue by Klemet** [gcyr/FMT#8]
I've seen that Moja Global uses [vcpkg ](https://en.wikipedia.org/wiki/Vcpkg) (open-source command-line utility from microsoft) to install several of the libraries needed [to compile FLINT](https://docs.moja.global/en/latest/prerequisites/vcpkg.html), and even [GCBM](https://github.com/moja-global/moja.canada).

Could vcpkg be used to make FMT easier to compile ? It should at least help to get boost, GDAL and others.

**Comment by Klemet** [comment]
Issue should be fixed, thanks to the instructions of @mfellows :

> Download and install Mosek
Clone the latest vcpkg from https://github.com/microsoft/vcpkg.git
From the command line in the vcpkg dir:
  Run bootstrap-vcpkg.bat
`  vcpkg install boost:x64-windows boost-dll:x64-windows boost-icl:x64-windows boost-python:x64-windows osi:x64-windows gdal:x64-windows geos:x64-windows`
Clone FMT and make a directory called ‘build’ inside the main directory
From the command line in <fmt dir>\build:
`  cmake -G "Visual Studio 16 2019" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=C:/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -DMOSEK_DIR=C:/path/to/Mosek ..`

I will try that on my side ASAP. If this works, I think that we can update the README for further install.

- [ ] Test by Clement on Windows 10
- [ ] Further testing on linux (?)
- [ ] Edit the README of the projet to reflect those instructions

**Comment by gcyr** [comment]
It should compile with vcpkg and VS2019 / VS2017 now thanks to @mfellows
